rmcs_executor:
  ros__parameters:
    update_rate: 1000.0

    components:
      # 电机硬件和 command Partner
      - rmcs_core::hardware::AngleMotorHardware -> angle_motor_hardware

      # ROS2 目标角度 -> 最短弧角度误差
      - rmcs_core::controller::AngleTargetController -> angle_target_controller

      # 外环：角度误差 -> 目标速度
      - rmcs_core::controller::pid::ErrorPidController -> angle_pid_controller

      # 内环：目标速度 - 实际速度 -> 控制力矩
      - rmcs_core::controller::pid::PidController -> velocity_pid_controller

      # 发布双环内部数据
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

angle_motor_hardware:
  ros__parameters:
    board_serial: ""

angle_target_controller:
  ros__parameters: {}

# 角度外环
angle_pid_controller:
  ros__parameters:
    # 最短弧角度误差 -> 目标速度
    measurement: /motor/control_angle_error
    control: /motor/control_velocity

    kp: 5.0
    ki: 0.0
    kd: 0.0

    # 目标速度限制
    output_min: -3.0
    output_max: 3.0

# 速度内环
velocity_pid_controller:
  ros__parameters:
    # 目标速度 - 实际速度 -> 控制力矩
    measurement: /motor/velocity
    setpoint: /motor/control_velocity
    control: /motor/control_torque

    # 实机验证参数
    kp: 1.0
    ki: 0.0005
    kd: 0.0

    integral_min: -100.0
    integral_max: 100.0

    integral_split_min: -1.0
    integral_split_max: 1.0

    # 力矩限制
    output_min: -0.2
    output_max: 0.2

value_broadcaster:
  ros__parameters:
    forward_list:
      # 角度外环输入
      - /motor/control_angle_error

      # 角度外环输出，也是速度内环目标
      - /motor/control_velocity

      # 电机真实速度
      - /motor/velocity

      # 速度内环输出
      - /motor/control_torque
