rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Dr16MotorControl -> dr16_motor_control

dr16_motor_control:
  ros__parameters:
    board_serial: ""
    max_target_velocity: 10.0
    